Alias /cgit-css "/usr/share/cgit/"
ScriptAlias / "/usr/lib/cgit/cgit.cgi/"
RedirectMatch ^/cgit$ /cgit/
<Directory "/usr/lib/cgit/">
   AllowOverride None
   Options ExecCGI FollowSymlinks
   Require all granted
   RLimitNPROC 5
</Directory>
